id: AF99E5B25
title: 'The Drum of Deathlessness: A Prayer for the Long Life of Minling Chung Rinpoche'
type: translation
pechas:
- ICF9E8E9F
- I23F644D5
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:02:53.350241
  last_modified_at: 2023-01-04 13:02:53.350246
  collections:
  - Minling Chung Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  ICF9E8E9F/8738: CBCB
  I23F644D5/F119: CBCB
